name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'
        cache: 'npm'

    - name: Install MariaDB and execute SQL file
      run: |
        sudo apt-get install mariadb-server
        mysql -u root -e "CREATE DATABASE test;"
        mysql -u root < ./sql.sql

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Start the server and run tests
      run: |
        npm start &
        npm run test
