name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run nodemon
        run: npm run nodemon &

      - name: Run Jest
        run: npm run jest
