name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Compile to TypeScript
        run: npx tsc
        
      - name: Start Server
        run: npm run start &

      - name: Run Test
        run: npx jest
